Remove duplicate labels causing error in kustomize build
$ kustomize build . --enable-helm

Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 11: mapping key "helm.sh/chart" already defined at line 10